version: '3.8'

services:
  # Backend service for development
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/data.db
      - USE_MOCK_AI=true
    volumes:
      - backend_data:/data
      - ./backend:/app  # Mount source code for development
    working_dir: /app
    command: ["go", "run", "cmd/main.go"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service for development  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app  # Mount source code for development
      - /app/node_modules  # Exclude node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge
